export type ThemeMode = 'soft' | 'sharp';

export const themes = {
  soft: {
    name: 'Soft Mode',
    emoji: '💅',
    tagline: 'You\'re doing amazing!',
    bg: 'bg-gradient-to-br from-pink-50 via-purple-50 to-blue-50',
    card: 'bg-white/70 backdrop-blur-sm border border-pink-100',
    cardHover: 'hover:bg-white/90 hover:border-pink-200',
    primary: 'bg-gradient-to-r from-pink-400 to-purple-400',
    primaryHover: 'hover:from-pink-500 hover:to-purple-500',
    primaryText: 'text-pink-500',
    primaryBorder: 'border-pink-300',
    secondary: 'bg-purple-100',
    secondaryText: 'text-purple-600',
    accent: 'bg-gradient-to-r from-purple-400 to-pink-400',
    text: 'text-gray-700',
    textMuted: 'text-gray-400',
    heading: 'text-gray-800',
    nav: 'bg-white/80 backdrop-blur-md border-b border-pink-100',
    button: 'bg-gradient-to-r from-pink-400 to-purple-400 text-white rounded-full shadow-md hover:shadow-lg hover:scale-105',
    buttonSecondary: 'bg-pink-50 text-pink-500 border border-pink-200 rounded-full hover:bg-pink-100',
    badge: 'bg-pink-100 text-pink-600 rounded-full',
    progress: 'bg-gradient-to-r from-pink-400 to-purple-400',
    progressBg: 'bg-pink-100',
    icon: 'text-pink-400',
    xpBar: 'from-pink-400 to-purple-500',
    shadow: 'shadow-pink-100',
    streakColor: 'text-orange-400',
    correct: 'bg-green-50 border-green-200 text-green-700',
    wrong: 'bg-red-50 border-red-200 text-red-600',
    gameCard: 'bg-gradient-to-br from-pink-100 to-purple-100',
    inputBg: 'bg-white/80 border-pink-200 focus:border-pink-400 focus:ring-pink-200',
    sidebar: 'bg-white/90 border-r border-pink-100',
    motivational: ['Ти се справяш невероятно! 💖', 'Продължавай! Страхотна си! ✨', 'Ти си суперзвезда! 🌟', 'Отлична работа! 💅', 'Горда съм от теб! 🎀'],
  },
  sharp: {
    name: 'Sharp Mode',
    emoji: '🖤',
    tagline: 'Focus. No excuses.',
    bg: 'bg-gray-950',
    card: 'bg-gray-900 border border-gray-800',
    cardHover: 'hover:bg-gray-800 hover:border-cyan-900',
    primary: 'bg-gradient-to-r from-cyan-500 to-blue-600',
    primaryHover: 'hover:from-cyan-400 hover:to-blue-500',
    primaryText: 'text-cyan-400',
    primaryBorder: 'border-cyan-700',
    secondary: 'bg-gray-800',
    secondaryText: 'text-cyan-400',
    accent: 'bg-gradient-to-r from-cyan-500 to-blue-500',
    text: 'text-gray-300',
    textMuted: 'text-gray-500',
    heading: 'text-white',
    nav: 'bg-gray-950/90 backdrop-blur-md border-b border-gray-800',
    button: 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white rounded-md shadow-lg shadow-cyan-900/30 hover:shadow-cyan-800/50 hover:scale-105',
    buttonSecondary: 'bg-gray-800 text-cyan-400 border border-gray-700 rounded-md hover:bg-gray-700',
    badge: 'bg-gray-800 text-cyan-400 rounded-sm',
    progress: 'bg-gradient-to-r from-cyan-500 to-blue-600',
    progressBg: 'bg-gray-800',
    icon: 'text-cyan-400',
    xpBar: 'from-cyan-500 to-blue-600',
    shadow: 'shadow-gray-900',
    streakColor: 'text-orange-400',
    correct: 'bg-green-950 border-green-800 text-green-400',
    wrong: 'bg-red-950 border-red-900 text-red-400',
    gameCard: 'bg-gradient-to-br from-gray-900 to-gray-800 border border-cyan-900/50',
    inputBg: 'bg-gray-800 border-gray-700 focus:border-cyan-500 focus:ring-cyan-900',
    sidebar: 'bg-gray-950 border-r border-gray-800',
    motivational: ['Концентрирай се.', 'Без оправдания.', 'Работата се върши сега.', 'Фокус. Издръжливост. Победа.', 'Ти знаеш материала. Докажи го.'],
  },
} as const;
